### ISSUE TITLE
Asana provider doesn't refresh tokens properly

### ISSUE THREAD

**Issue by t1mmen** [NangoHQ/nango#455]
### Steps to reproduce:
1. Connect Asana
2. Wait for token to expire
3. Attempt to `nangoClient.getToken()`

Outcome: `getToken` throw error: `Request failed with status code 500`

Heroku logs from step 3 below:
```
2023-04-04T17:37:12.940403+00:00 heroku[router]: at=info method=GET path="/connection/account_XXX?provider_config_key=asana-account" host=my.host.goes.here request_id=XXX fwd="3.127.85.XX" dyno=web.1 connect=0ms service=350ms status=500 bytes=398 protocol=https
2023-04-04T17:37:12.938791+00:00 app[web.1]: 2023-04-04T17:37:12.938Z [ERROR] Exception caught: {"stack":"Error: An unhandled error has occured: Response Error: 400 Bad Request\n    at ErrorManager.handleGenericError (file:///usr/nango-server/src/packages/server/dist/utils/error.manager.js:39:19)\n    at file:///usr/nango-server/src/packages/server/dist/server.js:84:18\n    at Layer.handle_error (/usr/nango-server/src/node_modules/express/lib/router/layer.js:71:5)\n    at trim_prefix (/usr/nango-server/src/node_modules/express/lib/router/index.js:326:13)\n    at /usr/nango-server/src/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/usr/nango-server/src/node_modules/express/lib/router/index.js:346:12)\n    at next (/usr/nango-server/src/node_modules/express/lib/router/index.js:280:10)\n    at next (/usr/nango-server/src/node_modules/express/lib/router/route.js:136:14)\n    at ConnectionController.getConnectionCreds (file:///usr/nango-server/src/packages/server/dist/controllers/connection.controller.js:150:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","status":500,"type":"unhandled_Response Error: 400 Bad Request","payload":{},"message":"An unhandled error has occured: Response Error: 400 Bad Request"}
```

Issue experienced on `nangohq/nango-server:0.11.2` -- will report back if updating to `0.13.0` resolves it.

**Comment by uncle-tee** [comment]
Hello @t1mmen, sorry for this issue. This is a bug and I have raised a [R for the fix. You will be able to get the refresh tokens as soon as the PR is approved.

**Comment by t1mmen** [comment]
Thanks @uncle-tee, appreciate you 🙏

**Comment by bastienbeurier** [comment]
Resolved by https://github.com/NangoHQ/nango/commit/25a9a4597dfcf65e7b380dadeb37128a3c436186
