### ISSUE TITLE
Request entity too large

### ISSUE THREAD

**Issue by khaliqgant** [NangoHQ/nango#692]
```
Exception caught: {"stack":"Error: An unhandled error has occurred: request entity too large\n    at ErrorManager.handleGenericError (file:///usr/nango-server/src/packages/shared/dist/lib/utils/error.manager.js:44:19)\n    at file:///usr/nango-server/src/packages/server/dist/server.js:111:18\n    at Layer.handle_error (/usr/nango-server/src/node_modules/express/lib/router/layer.js:71:5)\n    at trim_prefix (/usr/nango-server/src/node_modules/express/lib/router/index.js:326:13)\n    at /usr/nango-server/src/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/usr/nango-server/src/node_modules/express/lib/router/index.js:346:12)\n    at next (/usr/nango-server/src/node_modules/express/lib/router/index.js:280:10)\n    at Layer.handle_error (/usr/nango-server/src/node_modules/express/lib/router/layer.js:67:12)\n    at trim_prefix (/usr/nango-server/src/node_modules/express/lib/router/index.js:326:13)\n    at /usr/nango-server/src/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/usr/nango-server/src/node_modules/express/lib/router/index.js:346:12)\n    at next (/usr/nango-server/src/node_modules/express/lib/router/index.js:280:10)\n    at onfinished (/usr/nango-server/src/node_modules/body-parser/lib/read.js:102:9)\n    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n    at listener (/usr/nango-server/src/node_modules/on-finished/index.js:170:15)\n    at onFinish (/usr/nango-server/src/node_modules/on-finished/index.js:101:5)","status":500,"type":"unhandled_request entity too large","payload":{},"message":"An unhandled error has occurred: request entity too large","__sentry_captured__":true}
```

This could be application side or nginx side.

- [x] delete integration files on connection delete

**Comment by khaliqgant** [comment]
Body parser default limit is 100kb https://github.com/expressjs/body-parser/blob/ee91374eae1555af679550b1d2fb5697d9924109/README.md?plain=1#L249
