### ISSUE TITLE
[BUG] Empty encryption key in local build results in fatal error

### ISSUE THREAD

**Issue by MoSheikh** [NangoHQ/nango#914]
On the latest commit in `master`, running Nango locally via `docker compose` results in the following error when the `NANGO_ENCRYPTION_KEY` environment variable is either unset or set to an empty string in the `.env` file.

```
nango-server  | file:///usr/nango-server/src/packages/shared/dist/lib/utils/encryption.manager.js:14
nango-server  |             throw new Error('Encryption key must be base64-encoded and 256-bit long.');
nango-server  |                   ^
nango-server  |
nango-server  | Error: Encryption key must be base64-encoded and 256-bit long.
nango-server  |     at new EncryptionManager (file:///usr/nango-server/src/packages/shared/dist/lib/utils/encryption.manager.js:14:19)
nango-server  |     at file:///usr/nango-server/src/packages/shared/dist/lib/utils/encryption.manager.js:156:16
nango-server  |     at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
nango-server  |
nango-server  | Node.js v18.16.0
```

The `nango-server` container ends up going into a restart loop and becomes unable to process any requests.

**Comment by bastienbeurier** [comment]
Moved to internal issue tracker
